theme: minima
title: CATS ALL DAY 
author: CAT GOD
email: cat@cat.cat
description: > # this means to ignore newlines until "baseurl:"
  All your cats are belong to us.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
